use crate::models::{DetectedCapability, FileEntry, ScanReceipt};
use anyhow::{Context, Result};
use oxigraph::io::RdfFormat;
use oxigraph::model::*;
use oxigraph::store::Store;
use std::path::Path;

// Public vocabulary namespaces
const PROV:    &str = "http://www.w3.org/ns/prov#";
const DCAT:    &str = "http://www.w3.org/ns/dcat#";
const DOAP:    &str = "http://usefulinc.com/ns/doap#";
const SPDX:    &str = "http://spdx.org/rdf/terms#";
const SKOS:    &str = "http://www.w3.org/2004/02/skos/core#";
const DCTERMS: &str = "http://purl.org/dc/terms/";
const RDF_NS:  &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
const XSD:     &str = "http://www.w3.org/2001/XMLSchema#";

// ─── helpers ─────────────────────────────────────────────────────────────────

fn gate_iri(iri: &str) -> Result<NamedNode> {
    NamedNode::new(iri)
        .map_err(|e| anyhow::anyhow!("Gate[IRI]: invalid IRI `{iri}`: {e}"))
}

fn n(iri: &str) -> NamedNode {
    NamedNode::new(iri).expect("hard-coded IRI must be valid")
}


// ─── public entry point ──────────────────────────────────────────────────────

/// Build an in-memory RDF graph and serialise to Turtle, N-Quads, and SHACL
/// shapes under `out_dir`.
pub fn build_and_emit(
    files: &[FileEntry],
    capabilities: &[DetectedCapability],
    receipt: &ScanReceipt,
    out_dir: &Path,
) -> Result<()> {
    let store = Store::new().context("creating oxigraph store")?;

    let rdf_type  = n(&format!("{RDF_NS}type"));
    let xsd_dt    = n(&format!("{XSD}dateTime"));
    let xsd_int   = n(&format!("{XSD}integer"));

    // ── Catalog (DCAT) ────────────────────────────────────────────────────────
    let catalog = gate_iri(&format!("urn:cpmp:catalog:{}", receipt.id))?;
    insert_triple(&store, &catalog, &rdf_type, &n(&format!("{DCAT}Catalog")))?;
    insert_lit(&store, &catalog, &n(&format!("{DCTERMS}identifier")), &receipt.id, None)?;
    insert_lit(&store, &catalog, &n(&format!("{DCTERMS}issued")), &receipt.timestamp, Some(&xsd_dt))?;

    // ── Scan Activity (PROV-O) ────────────────────────────────────────────────
    let scan_node = gate_iri(&format!("urn:cpmp:scan:{}", receipt.id))?;
    insert_triple(&store, &scan_node, &rdf_type, &n(&format!("{PROV}Activity")))?;
    insert_lit(&store, &scan_node, &n(&format!("{PROV}startedAtTime")), &receipt.timestamp, Some(&xsd_dt))?;
    insert_lit(&store, &scan_node, &n(&format!("{DCTERMS}description")), "cpmp filesystem scan", None)?;

    // Catalog was generated by scan
    insert_triple(&store, &catalog, &n(&format!("{PROV}wasGeneratedBy")), &scan_node)?;

    // ── DOAP Project ──────────────────────────────────────────────────────────
    let project = n("urn:cpmp:project:local");
    insert_triple(&store, &project, &rdf_type, &n(&format!("{DOAP}Project")))?;
    insert_triple(&store, &catalog, &n(&format!("{DCAT}dataset")), &project)?;

    // ── Files (SPDX) ─────────────────────────────────────────────────────────
    for file in files {
        let path_str  = file.path.to_string_lossy();
        let file_node = gate_iri(&format!("file://{path_str}"))?;

        insert_triple(&store, &file_node, &rdf_type, &n(&format!("{SPDX}File")))?;
        insert_triple(&store, &file_node, &n(&format!("{PROV}wasGeneratedBy")), &scan_node)?;
        insert_lit(&store, &file_node, &n(&format!("{DCTERMS}format")), &file.language, None)?;
        insert_lit(&store, &file_node, &n(&format!("{SPDX}fileSize")), &file.size.to_string(), Some(&xsd_int))?;
        insert_triple(&store, &catalog, &n(&format!("{DCAT}distribution")), &file_node)?;

        // SPDX Checksum (BLAKE3)
        let cs_node = gate_iri(&format!("urn:cpmp:checksum:{}", file.hash))?;
        insert_triple(&store, &cs_node, &rdf_type, &n(&format!("{SPDX}Checksum")))?;
        insert_triple(&store, &cs_node, &n(&format!("{SPDX}algorithm")), &n("http://spdx.org/rdf/terms#checksumAlgorithm_blake3"))?;
        insert_lit(&store, &cs_node, &n(&format!("{SPDX}checksumValue")), &file.hash, None)?;
        insert_triple(&store, &file_node, &n(&format!("{SPDX}checksum")), &cs_node)?;
    }

    // ── Capabilities (SKOS) ───────────────────────────────────────────────────
    for cap in capabilities {
        let path_str  = cap.file_path.to_string_lossy();
        let file_node = gate_iri(&format!("file://{path_str}"))?;

        let slug     = cap.capability.replace(' ', "_");
        let cap_node = gate_iri(&format!("urn:cpmp:capability:{slug}"))?;

        insert_triple(&store, &cap_node, &rdf_type, &n(&format!("{SKOS}Concept")))?;
        insert_lit(&store, &cap_node, &n(&format!("{SKOS}prefLabel")), &cap.capability, None)?;
        insert_lit(&store, &cap_node, &n(&format!("{SKOS}notation")), &cap.classification.to_string(), None)?;
        // private instance predicate — not a namespace violation
        insert_triple(&store, &file_node, &n("urn:cpmp:implementsCapability"), &cap_node)?;
    }

    // ── Emit ──────────────────────────────────────────────────────────────────
    std::fs::create_dir_all(out_dir)?;

    // N-Quads (full dataset) — serializer then writer
    let nq_path = out_dir.join("cpmp-catalog.nq");
    let nq_file = std::fs::File::create(&nq_path)?;
    store
        .dump_to_writer(RdfFormat::NQuads, std::io::BufWriter::new(nq_file))
        .map_err(|e| anyhow::anyhow!("N-Quads dump failed: {e}"))?;

    // Turtle (default graph only) — graph_name, serializer, buffer
    let mut ttl_buf = Vec::new();
    store
        .dump_graph_to_writer(GraphNameRef::DefaultGraph, RdfFormat::Turtle, &mut ttl_buf)
        .map_err(|e| anyhow::anyhow!("Turtle dump failed: {e}"))?;
    let ttl_str = String::from_utf8(ttl_buf).context("invalid UTF-8 in Turtle dump")?;
    let prefixed_ttl = apply_prefixes(&ttl_str);
    let ttl_path = out_dir.join("cpmp-catalog.ttl");
    std::fs::write(&ttl_path, prefixed_ttl)?;

    // SHACL shapes
    std::fs::write(out_dir.join("cpmp-shapes.ttl"), SHACL_SHAPES)?;

    Ok(())
}

fn apply_prefixes(turtle: &str) -> String {
    let prefixes = r#"@prefix prov:    <http://www.w3.org/ns/prov#> .
@prefix dcat:    <http://www.w3.org/ns/dcat#> .
@prefix doap:    <http://usefulinc.com/ns/doap#> .
@prefix spdx:    <http://spdx.org/rdf/terms#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .

"#;

    let mut result = turtle.to_string();

    let mappings = [
        ("http://www.w3.org/ns/prov#", "prov:"),
        ("http://www.w3.org/ns/dcat#", "dcat:"),
        ("http://usefulinc.com/ns/doap#", "doap:"),
        ("http://spdx.org/rdf/terms#", "spdx:"),
        ("http://www.w3.org/2004/02/skos/core#", "skos:"),
        ("http://purl.org/dc/terms/", "dcterms:"),
        ("http://www.w3.org/1999/02/22-rdf-syntax-ns#", "rdf:"),
        ("http://www.w3.org/2001/XMLSchema#", "xsd:"),
    ];

    for (ns, prefix) in &mappings {
        let pattern = format!(r#"<{}([^>]+)>"#, regex::escape(ns));
        if let Ok(re) = regex::Regex::new(&pattern) {
            result = re.replace_all(&result, format!("{}$1", prefix)).to_string();
        }
    }

    format!("{}{}", prefixes, result)
}

// ─── insert helpers ──────────────────────────────────────────────────────────

fn insert_triple(store: &Store, s: &NamedNode, p: &NamedNode, o: &NamedNode) -> Result<()> {
    store
        .insert(QuadRef::new(
            NamedNodeRef::new(s.as_str()).unwrap(),
            NamedNodeRef::new(p.as_str()).unwrap(),
            NamedNodeRef::new(o.as_str()).unwrap(),
            GraphNameRef::DefaultGraph,
        ))
        .map(|_| ())
        .map_err(|e| anyhow::anyhow!("store insert triple failed: {e}"))
}

fn insert_lit(store: &Store, s: &NamedNode, p: &NamedNode, val: &str, dt: Option<&NamedNode>) -> Result<()> {
    let lit = match dt {
        Some(d) => Literal::new_typed_literal(val, d.as_ref()),
        None    => Literal::new_simple_literal(val),
    };
    store
        .insert(QuadRef::new(
            NamedNodeRef::new(s.as_str()).unwrap(),
            NamedNodeRef::new(p.as_str()).unwrap(),
            LiteralRef::from(&lit),
            GraphNameRef::DefaultGraph,
        ))
        .map(|_| ())
        .map_err(|e| anyhow::anyhow!("store insert literal failed: {e}"))
}

// ─── catalog source hash ──────────────────────────────────────────────────────

pub fn catalog_source_hash(ttl_path: &Path) -> Result<String> {
    let content = std::fs::read(ttl_path)?;
    Ok(blake3::hash(&content).to_hex().to_string())
}

// ─── SHACL shapes ─────────────────────────────────────────────────────────────

const SHACL_SHAPES: &str = r#"@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix spdx:  <http://spdx.org/rdf/terms#> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .

<#FileShape> a sh:NodeShape ;
    sh:targetClass spdx:File ;
    sh:property [
        sh:path prov:wasGeneratedBy ;
        sh:minCount 1 ;
        sh:class prov:Activity ;
        sh:name "Lineage link required" ;
    ] ;
    sh:property [
        sh:path spdx:checksum ;
        sh:minCount 1 ;
        sh:class spdx:Checksum ;
        sh:name "Checksum required" ;
    ] .

<#ChecksumShape> a sh:NodeShape ;
    sh:targetClass spdx:Checksum ;
    sh:property [
        sh:path spdx:checksumValue ;
        sh:minCount 1 ;
        sh:datatype xsd:string ;
        sh:name "Hash value required" ;
    ] .

<#CapabilityShape> a sh:NodeShape ;
    sh:targetClass skos:Concept ;
    sh:property [
        sh:path skos:prefLabel ;
        sh:minCount 1 ;
        sh:datatype xsd:string ;
        sh:name "Capability label required" ;
    ] ;
    sh:property [
        sh:path skos:notation ;
        sh:minCount 1 ;
        sh:name "Classification required" ;
    ] .
"#;
